import taigo from "./assets/images/Cars/taigo.png";
import polo from "./assets/images/Cars/polo.png";
import smart from "./assets/images/Cars/smart.png";
import yaris from "./assets/images/Cars/yaris.png";
import peugeot from "./assets/images/Cars/peugeot.png";
import fiesta from "./assets/images/Cars/fiesta.png";
import golf from "./assets/images/Cars/golf.png";
import clio from "./assets/images/Cars/clio.png";
import astra from "./assets/images/Cars/astra.png";
import ceed from "./assets/images/Cars/ceed.png";

export const cars = [
  {
    id: 1,
    name: "Volkswagen Taigo",
    type: "SUV",
    img: taigo,
    seats: 5,
    fuelType: "Petrol",
    transmission: "Automatic",
    features: ["Navigation", "Air Conditioning", "Bluetooth"],
    dailyRent: 65,
  },
  {
    id: 2,
    name: "Volkswagen Polo",
    type: "Economy",
    img: polo,
    seats: 5,
    fuelType: "Petrol",
    transmission: "Manual",
    features: ["Air Conditioning", "Bluetooth", "Rear Parking Sensors"],
    dailyRent: 45,
  },
  {
    id: 3,
    name: "Smart ForFour",
    type: "Mini",
    img: smart,
    seats: 4,
    fuelType: "Petrol",
    transmission: "Automatic",
    features: ["Compact Size", "Bluetooth", "Air Conditioning"],
    dailyRent: 40,
  },
  {
    id: 4,
    name: "Toyota Yaris",
    type: "Economy",
    img: yaris,
    seats: 5,
    fuelType: "Petrol",
    transmission: "Automatic",
    features: ["Hybrid Option", "Air Conditioning", "Touchscreen Display"],
    dailyRent: 50,
  },
  {
    id: 5,
    name: "Peugeot 208",
    type: "Economy",
    img: peugeot,
    seats: 5,
    fuelType: "Diesel",
    transmission: "Manual",
    features: ["Air Conditioning", "Bluetooth", "Advanced Safety Features"],
    dailyRent: 48,
  },
  {
    id: 6,
    name: "Ford Fiesta",
    type: "Economy",
    img: fiesta,
    seats: 5,
    fuelType: "Petrol",
    transmission: "Manual",
    features: ["Bluetooth", "Air Conditioning", "Rear Parking Sensors"],
    dailyRent: 46,
  },
  {
    id: 7,
    name: "Volkswagen Golf",
    type: "Compact",
    img: golf,
    seats: 5,
    fuelType: "Diesel",
    transmission: "Automatic",
    features: ["Navigation", "Bluetooth", "Advanced Safety Features"],
    dailyRent: 55,
  },
  {
    id: 8,
    name: "Renault Clio",
    type: "Economy",
    img: clio,
    seats: 5,
    fuelType: "Petrol",
    transmission: "Automatic",
    features: ["Air Conditioning", "Bluetooth", "Touchscreen Display"],
    dailyRent: 47,
  },
  {
    id: 9,
    name: "Opel Astra",
    type: "Compact",
    img: astra,
    seats: 5,
    fuelType: "Diesel",
    transmission: "Automatic",
    features: ["Navigation", "Bluetooth", "Air Conditioning"],
    dailyRent: 54,
  },
  {
    id: 10,
    name: "Kia Ceed",
    type: "Compact",
    img: ceed,
    seats: 5,
    fuelType: "Diesel",
    transmission: "Automatic",
    features: ["Air Conditioning", "Bluetooth", "Cruise Control"],
    dailyRent: 52,
  },
];
